//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveStreamProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LiveStreamDBEntities : DbContext
    {
        public LiveStreamDBEntities()
            : base("name=LiveStreamDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProfileTBL> ProfileTBLs { get; set; }
        public virtual DbSet<LoginTBL> LoginTBLs { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
    }
}
