//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveStreamProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileTBL
    {
        public int ProfileID { get; set; }
        public string FName { get; set; }
        public string SName { get; set; }
        public string HouseName_Number { get; set; }
        public string Street { get; set; }
        public string Town_City { get; set; }
        public string County { get; set; }
        public string PostCode { get; set; }
        public Nullable<System.DateTime> D_O_B { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public string Email { get; set; }
    }
}
